expsift/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'expsift.views.home', name='home'),
    url(r'^filter/$', 'expsift.views.filter', name='filter'),
    url(r'^update_expts/$', 'expsift.views.update_expts', name='update_expts'),
    url(r'^compare_expts/$', 'expsift.views.compare_expts_base',
        name='compare_expts'),
    url(r'^show_expt_directories/$', 'expsift.views.show_expt_directories',
        name='show_expt_dirs'),
    url(r'^individual_expt/$', 'expsift.views.individual_expt_base',
        name='individual_expt'),
    # url(r'^expsift/', include('expsift.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

expsift/views.py
# Create your views here.

from django.conf import settings
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from django.forms.widgets import SelectMultiple
from django.template import RequestContext
from django.core.urlresolvers import reverse
from django.forms import formsets
from django.forms.formsets import formset_factory
from django.utils import http
from django import forms
import base64
import datetime
import hashlib
import imp
import itertools
import os
import redis
import expsift.utils


class FilterForm(forms.Form):
    properties = forms.MultipleChoiceField(label='Filter Properties',
            widget=forms.SelectMultiple(attrs={'size':'10'}))
    choices = (('a','All'), ('g','Good only'),
               ('gu','Good or Unknown'),
               ('u','Unknown'), ('b','Bad'))
    goodbadfilter = forms.ChoiceField(widget = forms.RadioSelect,
                                      choices = choices)


    def __init__(self, properties = [], propValues = {}, *args, **kwargs):

        super(FilterForm, self).__init__(*args, **kwargs)

        propTuples = []
        for prop in sorted(properties):
            propTuples.append((prop, prop))

        self.fields['properties'].choices = propTuples

        for (property, pVals) in sorted(propValues.iteritems()):
            valTuples = []
            for val in sorted(pVals):
                valTuples.append((val, val))
            self.fields[property + '_values'] = forms.MultipleChoiceField(
                    label = property, choices = valTuples, required = False,
                    widget=forms.SelectMultiple(attrs={'size':'8'}))


# A custom BaseFormSet to create ExptForms with appropriate keyword arguments
# passed to the Form constructor
# The keyword argument 'unique_props' has to be a list of the set of unique
# properties for each ExptForm. The order of the sets in the list should be the
# same as the order of forms in the 'initial' keyword argument
class ExptBaseFormSet(formsets.BaseFormSet):

    def __init__(self, unique_props = [], *args, **kwargs):
        self.unique_props = unique_props
        super(ExptBaseFormSet, self).__init__(*args, **kwargs)


    def _construct_forms(self):
        # instantiate all the forms and put them in self.forms
        self.forms = []
        for i in xrange(self.total_form_count()):
            if self.unique_props:
                unique = self.unique_props[i]
            else:
                unique = []

            self.forms.append(self._construct_form(i, unique_props = unique))


class ExptForm(forms.Form):

    # Absolute directory path
    directory = forms.CharField(widget=forms.HiddenInput(),
                                required=False)

    # (Shortened) name displayed for the directory
    directory_display = forms.CharField(widget=forms.HiddenInput(),
                                        required=False)

    # URL of experiment directory
    directory_url = forms.CharField(widget=forms.HiddenInput(),
                                    required=False)

    # When was the experiment conducted? (Actually just the timestamp value
    # stored in the expsift_info file)
    timestamp = forms.DateTimeField(
            required = False,
            input_formats = ['%Y-%m-%d_%H:%M:%S.%f',
                             '%Y-%m-%d %H:%M:%S.%f',
                             '%Y-%m-%d_%H:%M:%S',
                             '%Y-%m-%d %H:%M:%S'])

    # Experiment is marked as good/bad/unknown
    expt_good = forms.NullBooleanField(
            required = False,
            widget=forms.Select(choices = ((None, 'Unknown'),
                                           (True, 'Good'),
                                           (False, 'Bad'))))

    # Properties from the expsift_tags file (text read from the file)
    properties_file = forms.CharField(required=False,
            widget=forms.Textarea(attrs={'rows':'8', 'cols':'30'}))
    properties_file_hidden = forms.CharField(widget=forms.HiddenInput(),
                                             required=False)

    # Comments from the expsift_comments file (text read from the file)
    comments_file = forms.CharField(required=False,
            widget=forms.Textarea(attrs={'rows':'8', 'cols':'40'}))
    comments_file_hidden = forms.CharField(widget=forms.HiddenInput(),
                                           required=False)

    # Is the experiment selected for comparison?
    compare_expt_select = forms.BooleanField(required=False)

    def __init__(self, unique_props = [], *args, **kwargs):
        super(ExptForm, self).__init__(*args, **kwargs)
        self.unique_properties = unique_props
        # Store the properties for the directory in a custom HTML5 data
        # attribute for the directory's checkbox.
        if unique_props:
            props_str = ' '.join([x.replace(' ', '___', 1) for x in unique_props])
            select_box = self.fields['compare_expt_select']
            select_box.widget.attrs.update({'data-expsift-uniq-props' : props_str})


class SelectDialogForm(forms.Form):

    def __init__(self, propValues = {}, *args, **kwargs):

        super(SelectDialogForm, self).__init__(*args, **kwargs)

        for (pName, pVals) in sorted(propValues.iteritems()):
            valTuples = []
            for val in sorted(pVals):
                valTuples.append((val, val))
            self.fields[pName+ '_values'] = forms.MultipleChoiceField(
                    label = pName, choices = valTuples, required = False,
                    widget=forms.SelectMultiple(attrs={'size':'8'}))


def redis_connect(host, port):
    properties_db = redis.StrictRedis(host, port, db=0)
    dir2properties_db = redis.StrictRedis(host, port, db=1)
    properties2dir_db = redis.StrictRedis(host, port, db=2)
    sha12dir_db = redis.StrictRedis(host, port, db=3)

    # Validate magic number keys of the databases
    assert(properties_db.get('magic_number') == '16378267')
    assert(dir2properties_db.get('magic_number') == '76378347')
    assert(properties2dir_db.get('magic_number') == '324728749')
    assert(sha12dir_db.get('magic_number') == '39916801')

    # Return a tuple with all 3 databases
    return (properties_db, dir2properties_db, properties2dir_db, sha12dir_db)


def getProperties(prop_db):
    propNames = prop_db.keys()
    propNames.remove('magic_number')

    propsDict = {}
    for pName in propNames:
        propsDict[pName] = prop_db.smembers(pName)

    return propsDict


def filterDirectories(prop2dir_db, crossVals):
    res_directories = set()
    for keys in crossVals:
        if not keys:
            continue
        directories = prop2dir_db.sinter(*keys)
        res_directories |= directories

    return res_directories


def getDirProperties(dir2prop_db, directories):
    res_props = {}
    for dir in directories:
        props = dir2prop_db.smembers(dir)
        res_props[dir] = props

    return res_props


def getDirTimestamps(dir2prop_db, directories):
    res_timestamps = {}
    for dir in directories:
        ts = dir2prop_db.get(dir + '__timestamp')
        if not ts:
            ts = '1970-01-01_00:00:00.000001'  # Default value
        res_timestamps[dir] = ts

    return res_timestamps


def getDirGood(dir2prop_db, directories):
    res_good = {}
    for dir in directories:
        expt_good = dir2prop_db.get(dir + '__goodbad')
        if expt_good == 'GOOD':
            res_good[dir] = True
        elif expt_good == 'BAD':
            res_good[dir] = False

    return res_good


def readDirTagsFiles(directories):
    max_file_size = getattr(settings, 'MAX_EXPSIFT_TAGS_FILE_SIZE', -1)
    res_files = {}
    for dir in directories:
        if (os.path.exists(os.path.join(dir, 'expsift_tags'))):
            tags_file = open(os.path.join(dir, 'expsift_tags'), 'r')
            str = tags_file.read(max_file_size)
            tags_file.close()
            res_files[dir] = str

    return res_files


def directoryActualUrl(directory):
    expt_logs_conf = getattr(settings, 'EXPT_LOGS', {})
    expt_logs_dir = expt_logs_conf['directory']
    return (reverse('expsift.views.home') +
            'expt-logs/' +  directory[len(expt_logs_dir):])


def directoryExptPageUrl(directory):
    return (reverse('expsift.views.individual_expt_base') + '?' +
            http.urlencode({'directory' : directory}, True))


def readDirCommentsFiles(directories):
    max_file_size = getattr(settings, 'MAX_EXPSIFT_COMMENTS_FILE_SIZE', -1)
    res_files = {}
    for dir in directories:
        if (os.path.exists(os.path.join(dir, 'expsift_comments'))):
            comments_file = open(os.path.join(dir, 'expsift_comments'), 'r')
            str = comments_file.read(max_file_size)
            comments_file.close()
            res_files[dir] = str

    return res_files


def createExptFormset(directories, dir2good_dict, dir2timestamps_dict,
                      dir2tagsfile_dict, dir2commentsfile_dict, unique_props):
    initial_form_data = []
    expt_logs_conf = getattr(settings, 'EXPT_LOGS', {})
    expt_logs_dir = expt_logs_conf['directory']
    expt_dir_max_len = expt_logs_conf['max_dir_length']
    ExptFormSet = formset_factory(ExptForm, formset = ExptBaseFormSet,
                                  extra=0, max_num=len(directories))
    unique_properties = []
    for dir in directories:
        # Ignore entry if the directory is not in the expt-logs root directory
        if not dir.startswith(expt_logs_dir):
            continue
        initial_dict = {}
        initial_dict['directory'] = dir
        dir_shortname = dir[ dir.rfind('/') + 1 : ][ : expt_dir_max_len]
        if len(dir) > len(dir_shortname):
            dir_shortname += '...'
        initial_dict['directory_display'] = dir_shortname
        if getattr(settings, 'ENABLE_INDIVIDUAL_EXPT_PAGE', False):
            initial_dict['directory_url'] = directoryExptPageUrl(dir)
        else:

templates/home/expt_directories.html
<!DOCTYPE html>
<html lang="en">
<head>
     <title>ExpSift Home</title>
</head>

<body>
<style>
    td {padding: 5px;}
</style>

<table>
{% for directory,props in unique_props %}
    <tr> <td>{{ props }}</td><td>{{ directory }}</td> </tr>
{% endfor %}
</table>

</body>
</html>

templates/home/expts.html
{% load expsift_custom_filters %}
{% load staticfiles %}

{% comment %}
<form action="{% url expsift.views.update_expts %}?{{ url_parameters }}" method="POST">
<input type="submit" name="update_expts" value="Update Experiments"/> <br>
<table border="1">
<tr><th>Experiment</th><th>Properties</th><th>Comments</th></tr>

{% for dir in res_directories %}
    <tr>
        <td>{{ dir }}</td>
        <td>
            {% if dir2tagsfile_dict and dir2tagsfile_dict|get_item:dir %}
                <textarea name = "{{dir}}_tags" rows="8" cols="20">{{ dir2tagsfile_dict|get_item:dir }}</textarea>
            {% else %}
                <font color="red">Tags file not present.</font>
            {% endif %}
        </td>
        <td>
            <textarea name = "{{dir}}_comments" rows="8" cols="40">{% if dir2commentsfile_dict and dir2commentsfile_dict|get_item:dir %}{{ dir2commentsfile_dict|get_item:dir }}{% endif %}</textarea>
        </td>
    </tr>
{% endfor %}

</table>
</form>
{% endcomment %}

{% comment %}
{% for dir, dirProps in dir2props_dict.items %}
    <p>
    {{ dir }}
    {% for prop in dirProps %}
        {{ prop }}
    {% endfor %}
    </p>
{% endfor %}
{% endcomment %}


{% if expt_formset %}

<!-- Dialog box for selecting experiments -->
<div id="dialog-form" title="Experiment selector">
    <form>
    {% for field in select_dialog_form %}
        <div id="div_{{ field.label }}" class="inline" align="center">
        <p align="left">{{ field.errors }}</p>
        <p align="center">{{ field.label_tag }}</p>
        {{ field }}
        </div>
    {% endfor %}
    </form>
</div>


<!-- Dialog box for setting new tag -->
<div id="dialog-expt-tag" title="Set new tag">
    <form id="expt_tag_form">
        <label for="old_property_name">Old Property name</label>
        <input type="text" name="old_prop_name"/>
        <label for="old_property_val">Old Property value</label>
        <input type="text" name="old_prop_value"/>
        <label for="new_property_name">New Property name</label>
        <input type="text" name="new_prop_name"/>
        <label for="new_property_val">New Property value</label>
        <input type="text" name="new_prop_value"/>
    </form>
</div>


<style type="text/css">
    div#dialog-form label, div#dialog-form input { display:block; }
    div#dialog-form { font: 62.5% "Verdana", sans-serif; }
    div#dialog-form label, div#dialog-form p { font-size: 1.2em; line-height: 1.5; }

    div#dialog-expt-tag label, div#dialog-expt-tag input { display:block; }
    div#dialog-expt-tag { font: 62.5% "Verdana", sans-serif; }
    div#dialog-expt-tag label, div#dialog-expt-tag p { font-size: 1.2em; line-height: 1.5; }
</style>

<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js"></script>
<link rel=StyleSheet href="{% static 'css/jquery-ui-1.8.20.custom.css'%}" type="text/css" media=screen>

<script type="text/javascript">
    $(document).ready(function() {
        $('input[name="selectall"]').click(function() {
            if ($(this).attr('checked')) {
                $("#id_expt_forms :checkbox").attr('checked', 'checked');
            } else {
                $("#id_expt_forms :checkbox").removeAttr('checked');
            }
        });
    });
</script>

<script>
    $(document).ready(function() {

        $("#sel_filter_button").click(function() {
            $("#dialog-form").dialog( "open" );
        });

        $("#add_tag_button").click(function() {
            if ($("#id_expt_forms :checkbox:checked").length == 0) {
                alert("No experiments selected")
            } else {
                $("#dialog-expt-tag").dialog( "open" );
            }
        });

        $("#dialog-form").dialog({
            autoOpen: false,
            height: "auto",
            width: "auto",
            modal: true,
            buttons: {
                "Select": function() {
                    // Find what property values have been selected and
                    // construct an array 'cross' which has the cross product of
                    // selected property value strings
                    var first = true;
                    var cross = [];
                    $("#dialog-form select").each(function() {
                        var values = $(this).val();
                        var prop_name = $(this).attr('name');
                        prop_name = prop_name.substr(0, prop_name.length - 7);
                        prop_name_match = prop_name.replace(' ', '___');
                        if (values == null)
                            return;
                        var cross_new = []
                        $(values).each(function() {
                            value = this;
                            value_match = value.replace(' ', '___');
                            if (cross.length == 0) {
                                cross_new.push(['[data-expsift-uniq-props~="' + prop_name_match + '=' + value_match + '"]']);
                            } else {
                                $(cross).each(function(i) {
                                    cross_new.push(cross[i] + '[data-expsift-uniq-props~="' + prop_name_match + '=' + value_match + '"]');
                                });
                            }
                        });
                        cross = cross_new;
                        first = false;
                    });
                    // Select all the checkboxes corresponding to the
                    // filtered experiments
                    var selected_total = 0;
                    var selected_already = 0;
                    $(cross).each(function(i) {
                        var checkboxes = $("#id_expt_forms " + this + ":checkbox");
                        selected_total += checkboxes.length;
                        selected_already += $($(checkboxes).selector + ":checked").length;
                        $(checkboxes).attr('checked', 'checked');
                    });
                    $(this).dialog("close");
                    var selected_new = selected_total - selected_already;
                    alert("Selected " + selected_total + " (" + selected_new + " new)");
                },
                Cancel: function() {
                    $(this).dialog("close");
                }
            },
        });

        $("#dialog-expt-tag").dialog({
            autoOpen: false,
            height: "auto",
            width: "auto",
            modal: true,
            buttons: {
                "Add": function() {
                    $(this).dialog("close");
                    var old_prop_name = $("#expt_tag_form :input[name='old_prop_name']").val();
                    var old_prop_value = $("#expt_tag_form :input[name='old_prop_value']").val();
                    var new_prop_name = $("#expt_tag_form :input[name='new_prop_name']").val();
                    var new_prop_value = $("#expt_tag_form :input[name='new_prop_value']").val();
                    var old_prop_name_hidden = $("<input>").attr("type", "hidden").attr("name", "update_old_prop_name").val(old_prop_name);
                    var old_prop_value_hidden = $("<input>").attr("type", "hidden").attr("name", "update_old_prop_value").val(old_prop_value);
                    var new_prop_name_hidden = $("<input>").attr("type", "hidden").attr("name", "update_new_prop_name").val(new_prop_name);
                    var new_prop_value_hidden = $("<input>").attr("type", "hidden").attr("name", "update_new_prop_value").val(new_prop_value);
                    if (new_prop_name == "") {
                        alert("New property name not specified");
                        return;
                    } else if (new_prop_value == "") {
                        alert("New property value not specified");
                        return;
                    }

                    $("#update_form").append($(old_prop_name_hidden));
                    $("#update_form").append($(old_prop_value_hidden));
                    $("#update_form").append($(new_prop_name_hidden));
                    $("#update_form").append($(new_prop_value_hidden));

                    var update_expts_operation_hidden =
                    $("<input>").attr("type", "hidden").attr("name", "update_expts_operation").val("Update Tag");
                    $("#update_form").append($(update_expts_operation_hidden));

                    $("#update_form").submit();
                },
                Cancel: function() {
                    $(this).dialog("close");
                }
            }
        });

    });
</script>


<!-- Display experiments -->
<form id="update_form" action="{% url expsift.views.update_expts %}?{{ url_parameters }}" method="POST"> {% csrf_token %}

{{ expt_formset.management_form }}


<!-- Show experiment actions and number of results -->
<table> <tr>

<td style="padding-right:10px"> <input type="checkbox" name="selectall" value="Select All" /> Select All </td>

<td style="padding-right:10px"> <input type="submit" name="update_expts_operation" value="Update Experiments"/> </td>

<td style="padding-right:10px"> <input id="add_tag_button" class="inp_button" type="button" name="add_tag" value="Update Tag"/> </td>

<td style="padding-right:10px"> <input type="submit" name="update_expts_operation" value="Show Expt Dirs"/> </td>

<td style="padding-right:10px"> <input id="sel_filter_button" class="inp_button" type="button" name="Selection filter" value="Selection Filter"/> </td>

{% for compare_op in compare_operations %}
    <td style="padding-right:10px"> <input type="submit" name="update_expts_operation" value="{{ compare_op }}"/> </td>
{% endfor %}


<td>Showing {{ expt_formset.total_form_count }} results</td>

</tr> </table>
<br>


<!-- Show experiment directory results -->
<div id="id_expt_forms">
<table border="1">

<tr>
    <th>Select</th>
    <th>Experiment</th>
    <th>Good/Bad</th>
    <th>Unique Properties</th>
    <th>Properties</th>
    <th>Comments</th>
</tr>

{% for form in expt_formset %}
<tr>
    <td align="center">{{ form.compare_expt_select }}</td>
    <td><a href="{{ form.directory_url.value }}">{{ form.directory_display.value }}</a>{{form.directory}}</td>
    <td>{{ form.expt_good }}</td>
    <td style="padding-left:5px; padding-right:5px">
        {% for prop in form|get_expt_unique_props %}
            {{ prop }}<br>
        {% endfor %}
    </td>
    {% if form.properties_file.value %}
        <td>{{ form.properties_file }}{{ form.properties_file_hidden }}</td>
    {% else %}
        <td><font color = "red">Tags not found in file!{{ form.properties_file_hidden }}</font></td>
    {% endif %}
    <td>{{ form.comments_file }}{{ form.comments_file_hidden }}</td>
</tr>


{% comment %}
        <td>{{ dir }}</td>
        <td>
            {% if dir2tagsfile_dict and dir2tagsfile_dict|get_item:dir %}
                <textarea name = "{{dir}}_tags" rows="8" cols="20">{{ dir2tagsfile_dict|get_item:dir }}</textarea>
            {% else %}
                <font color="red">Tags file not present.</font>
            {% endif %}
        </td>
        <td>
            <textarea name = "{{dir}}_comments" rows="8" cols="40">{% if dir2commentsfile_dict and dir2commentsfile_dict|get_item:dir %}{{ dir2commentsfile_dict|get_item:dir }}{% endif %}</textarea>
        </td>
{% endcomment %}



{% endfor %}

</table>
</div>
</form>
{% endif %}

templates/home/index.html
<!DOCTYPE html>
<html lang="en">
<head>
     <title>ExpSift Home</title>
</head>

<body>

<script type="text/javascript" src="http://code.jquery.com/jquery-1.7.2.min.js"></script>

{% if propsDict %}

    <style type="text/css">
        div.inline { float:left; }
        div.inline { margin:10px; }
        .clearBoth { clear:both; }
        #filter_values{ overflow:hidden; zoom: 1; }
        div.sift_filter { float:left; }
        div.sift_filter { overflow:hidden; zoom: 1; }
        div.sift_filter { border: 2px dashed black; }
        div.sift_filter { padding: 5px; }
        div.sift_filter { height: 100%; }
        div.parent { overflow:hidden; zoom:1; }
    </style>

    <script type="text/javascript">

        var filterChangeFunc = function() {
            $("#id_properties option").each(function () {
                var sel = $(this).attr('selected');
                if (sel)
                    $("#div_"+$(this).text()).slideDown();
                else
                    $("#div_"+$(this).text()).hide();
            });
        };

        $(document).ready(function() {
            filterChangeFunc();
            $("#id_properties").change(filterChangeFunc);
        });

    </script>

    <form action="{% url expsift.views.filter %}" method="GET">
    <div id="parent" class="parent">

    <div id="sift_filter" class="sift_filter">
    {% with field=form.properties %}
    <p align="center">{{ field.errors}}</p>
    <p align="center">{{ field.label_tag}}</p>
    <p align="center">{{ field }}</p>
    {% endwith %}
    <p align="center">
    <input type="submit" name="operation" value="Filter"/> <br>
    <input type="reset" value="Clear"/> <br>
    <input type="submit" name="operation" value="Home"/>
    </p>
    </div>

    <div id="filter_values">
    {% for field in form %}
        {% if field.html_name != "properties" %}
        {% if field.html_name != "goodbadfilter" %}
        <div id="div_{{ field.label }}" class="inline" align="center">
        <p align="left">{{ field.errors}}</p>
        <p align="center">{{ field.label_tag}}</p>
            {{ field }}
        </div>
        {% endif %}
        {% endif %}
    {% endfor %}
    </div>

    </div> {# parent div #}
    <hr/>

    <p align="left">
    Validity filter:
    {% for radio in form.goodbadfilter %}
    {{ radio }}
    {% endfor %}
    <input type="submit" name="operation" value="Refresh view"/> <br>
    </p>

    </form>
    <hr/>

    {% if show_prop_val_error == '1' %}
        <p>Select values for properties</p>
    {% endif %}

    {% if show_no_results_error == '1' %}
        <p>No results found</p>
    {% else %}
        {% if res_directories %}
        <div id="results" class="results">
        {% include "home/expts.html" %}
        </div>
        {% endif %}
    {% endif %}

{% else %}

    <p>No properties available</p>

{% endif %}

</body>
</html>